### ISSUE TITLE
ModuleNotFoundError: No module named 'google.genai'

### ISSUE THREAD

**Issue by PBenavides** [saharmor/gemini-multimodal-playground#2]
There are some error apparently due to deprecations. I am new with the google API and I tried to install this module cause this repo seems amazing but couldn't get more beyond the google.genai installation. 

python standalone.py
Traceback (most recent call last):
  File "/Users/pablobenavides/Desktop/Code_and_Projects/gemini-multimodal-playground/standalone/standalone.py", line 3, in <module>
    from config_gui import ConfigGUI
  File "/Users/pablobenavides/Desktop/Code_and_Projects/gemini-multimodal-playground/standalone/config_gui.py", line 8, in <module>
    from gemini_connection import GeminiConnection
  File "/Users/pablobenavides/Desktop/Code_and_Projects/gemini-multimodal-playground/standalone/gemini_connection.py", line 9, in <module>
    from google.genai.types import (GoogleSearch,Tool, GenerateContentConfig)
ModuleNotFoundError: No module named 'google.genai'

I have the following related libraries installed:

google-generativeai       0.8.3                    pypi_0    pypi
google                    3.0.0                    pypi_0    pypi
google-ai-generativelanguage 0.6.10                   pypi_0    pypi

And I am confused since blogs in stackoverflows import this module such as:

import google.generativeai as genai

Any advice? What are the libraries version that this module use?

**Comment by saharmor** [comment]
Hey @PBenavides! How did you install your virtual environment? Did you follow the [readme](https://github.com/saharmor/gemini-multimodal-playground?tab=readme-ov-file#installation)?

When I run: `pip show google-genai`

I get version 0.2.2:
```
Name: google-genai
Version: 0.2.2
Summary: GenAI Python SDK
Home-page: https://github.com/googleapis/python-genai
Author: 
Author-email: Google LLC <googleapis-packages@google.com>
License: Apache-2.0
```

**Comment by PBenavides** [comment]
Yep. It seems to be the Python version. I switched from python 3.13 to 3.9 and it works. Also, I noticed that torchaudio and python-dotenv are needed but are not included in the requirements.txt.

Now I have succesufully started the app but still encountered some error regarding the packages. Now I am stuck with:

`Error in Gemini connection: module 'asyncio' has no attribute 'TaskGroup'`

Maybe a docker version or a more detailed information about the packages would help a lot. Thanks for creting this repo!

**Comment by PBenavides** [comment]
Yes. I changed again to Python 3.12.8 and it works since the asyncio version now have the TaskGroup attribute. The error is due to the Python version. This needs to be specified in the repo I'd say.

Name: google-genai
Version: 0.2.2
Summary: GenAI Python SDK
Home-page: https://github.com/googleapis/python-genai
Author: 
Author-email: Google LLC <googleapis-packages@google.com>
License: Apache-2.0
