### ISSUE TITLE
“I need to know which Python version is required for this project. I have tested with Python 3.11 and 3.10, but neither worked. Is there a specific version that I should use?”

### ISSUE THREAD

**Issue by xiaoyaoz1** [saharmor/gemini-multimodal-playground#7]
“I need to know which Python version is required for this project. I have tested with Python 3.11 and 3.10, but neither worked. Is there a specific version that I should use?”

**Comment by xiaoyaoz1** [comment]
（venv）jibenqing@JideMac-mini-2独立%python standalone.py回溯（最近一次通话）：文件“/Users/jibenqing/gemini-multimodal-playground/standalone/standalone.py”，第3行，在<模块>中从config_gui导入ConfigGUI文件“/Users/jibenqing/gemini-multimodal-playground/standalone/config_gui.py”，第3行，在<module>中将tkinter导入为tk文件“/opt/homebrew/Cellar/python@3.11/3.11.11/Frameworks/Python.framework/Versions/3.11/lib/python3.11/tkinter/__init__.py”，第38行，在<模块>中导入_tkinter #如果失败，您的Python可能无法配置为Tk^^^^^^^^^^^^^^^^^ModuleNotFoundError：没有名为“_tkinter”的模块（venv）jibenqing@JideMac-mini-2独立%

3.11.11

**Comment by xiaoyaoz1** [comment]
错误：忽略以下需要不同python版本的版本：1.21.2需要-Python >=3.7,<3.11; 1.21.3需要-Python >=3.7,<3.11; 1.21.4需要-Python >=3.7,<3.11; 1.21.5需要-Python >=3.7,<3.11; 1.21.6需要-Python >=3.7,<3.11; 1.26.0需要-Python <3.13,>=3.9; 1.26.1需要-Python <3.13,>=3.9错误：找不到满足火炬要求的版本（来自版本：无）错误：未找到火炬的匹配分布

3.13

**Comment by xiaoyaoz1** [comment]
ERROR: Ignored the following versions that require a different python version: 1.21.2 Requires-Python >=3.7,<3.11; 1.21.3 Requires-Python >=3.7,<3.11; 1.21.4 Requires-Python >=3.7,<3.11; 1.21.5 Requires-Python >=3.7,<3.11; 1.21.6 Requires-Python >=3.7,<3.11; 1.26.0 Requires-Python <3.13,>=3.9; 1.26.1 Requires-Python <3.13,>=3.9
ERROR: Could not find a version that satisfies the requirement torch (from versions: none)
ERROR: No matching distribution found for torch

3.13

**Comment by xiaoyaoz1** [comment]
(venv) mac@Mac-mini-2 standalone %    python standalone.py
Traceback (most recent call last):
  File "/Users/jibenqing/gemini-multimodal-playground/standalone/standalone.py", line 3, in <module>
    from config_gui import ConfigGUI
  File "/Users/jibenqing/gemini-multimodal-playground/standalone/config_gui.py", line 3, in <module>
    import tkinter as tk
  File "/opt/homebrew/Cellar/python@3.11/3.11.11/Frameworks/Python.framework/Versions/3.11/lib/python3.11/tkinter/__init__.py", line 38, in <module>
    import _tkinter # If this fails your Python may not be configured for Tk
    ^^^^^^^^^^^^^^^
ModuleNotFoundError: No module named '_tkinter'

**Comment by cheesecake100201** [comment]
if you are using a mac please install through terminal
```brew install python-tk@3.11```
Change 3.11 with version you want

**Comment by PBenavides** [comment]
I had the same problem. Mac M1. I am using Python 3.12 after a few attempts with other python versions and it works.

**Comment by saharmor** [comment]
Just clarified in the readme. Thanks both @PBenavides @cheesecake100201
